# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile.dev                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pguthaus <pguthaus@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/02/18 19:17:34 by pguthaus          #+#    #+#              #
#    Updated: 2019/03/25 16:21:02 by pguthaus         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Sources sets
-include make/sources.mk
-include libft/make/srcs.mk

UNAME_S 		:=			$(shell uname)

# Output name
NAME			=			fdf_dev

# Compilation
CC				=			clang
CFLAGS			=			-g

# Paths
SRCDIR			=			./src/
INCDIR			=			./includes/
OUTDIR			=			./objs/dev/

# Libft
FT_INC			=			libft/includes

# MLX
MLX_INC			=			/usr/local/include
MLX_ARGS		=			$(shell pkg-config --libs --static mlx)
ifeq ($(UNAME_S),Darwin)
MLX_ARGS		=			-L /usr/local/lib -lmlx -framework OpenGL -framework AppKit
endif

# OBJS
OBJS			=			$(addprefix $(OUTDIR),$(SRCS:.c=.o))
FT_OBJS			=			$(addprefix ./libft/objs/dev/,$(FT_SRCS:.c=.o))

dev: $(NAME)

re: fclean $(NAME)

$(NAME): $(OBJS)
	@$(CC) $(CFLAGS) $(OBJS) $(FT_OBJS) $(MLX_ARGS) -o $(NAME)

$(OUTDIR)%.o: $(SRCDIR)%.c
	@if [ ! -d $(dir $@) ]; then mkdir -p $(dir $@); fi
	@$(CC) $(CFLAGS) -I $(INCDIR) -I $(FT_INC) -I $(MLX_INC) -o $@ -c $<

clean:
	@rm -f $(OBJS)

fclean:
	@rm -rf $(NAME)
